# Generated by Django 3.0.3 on 2020-02-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20200208_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='reference_no',
            field=models.CharField(max_length=50),
        ),
    ]
