# Generated by Django 2.2.1 on 2020-02-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20200208_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
