# Generated by Django 3.0.3 on 2020-02-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20200208_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
